# Generated by Django 3.2 on 2024-10-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSalida', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('Genero', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
                ('Pegi', models.CharField(max_length=50)),
                ('Plataforma', models.CharField(max_length=50)),
            ],
        ),
    ]
